http:
  middlewares:
    secureHeaders:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        permissionsPolicy: "vibrate none"
    setu-redirect:
      redirectScheme:
        scheme: https

  routers:
    setu-http:
      rule: "Host(`setu.jira-plus-plus.in`)"
      entryPoints:
        - web
      middlewares:
        - setu-redirect
      service: setu-web

    setu-websecure:
      rule: "Host(`setu.jira-plus-plus.in`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - secureHeaders
      service: setu-web

    setu-api-http:
      rule: "Host(`setu-api.jira-plus-plus.in`)"
      entryPoints:
        - web
      middlewares:
        - setu-redirect
      service: setu-relay

    setu-api-websecure:
      rule: "Host(`setu-api.jira-plus-plus.in`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - secureHeaders
      service: setu-relay

  services:
    setu-web:
      loadBalancer:
        servers:
          - url: "http://setu_web:80"

    setu-relay:
      loadBalancer:
        servers:
          - url: "http://relay-relay-1:18080"
